import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import { Button, List, ListItem, Stack, Typography } from '@mui/material';
import CampTipeItem from '../../components/CampTipeItem';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className={styles.main}>
				<Typography variant='h1'>Hai cu noi in tabara</Typography>
				<Typography variant='body1'>
					Tabere de schi, Scoala de schi, E-bike, Schi de tura, Tabere de vara
					la munte!
				</Typography>
				<Button variant='contained'>Contacteaza-ne</Button>
				<Image src={'/Hero.png'} alt='hero' width={500} height={500} />
				<List>
					<BenefitItem
						icon={'/benefits/Brain.svg'}
						description={'Deprinderea de cunostinte noi'}
					/>
					<BenefitItem
						icon={'/benefits/Yoga.svg'}
						description={'Joaca, relaxare si distractie'}
					/>
					<BenefitItem
						icon={'/benefits/LifeStyle.svg'}
						description={'Incurajarea unui stil de viata activ'}
					/>
					<BenefitItem
						icon={'/benefits/forest.svg'}
						description={'Conectare cu mediul inconjurator'}
					/>
				</List>
				<Section title={'Despre noi'}>
					<Typography variant='body1' textAlign={'center'}>
						Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
						eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim
						ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
						aliquip ex ea commodo consequat. Duis aute irure dolor in
						reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla
						pariatur.
					</Typography>
				</Section>

				<Section title='Tipuri de tabere'>
					<List>
						<CampTipeItem
							imgSrc={'/camp-types/SummerCamp.png'}
							title={'Tabere de vara'}
							description={
								'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris '
							}
							link={''}
						/>
						<CampTipeItem
							imgSrc={'/camp-types/Bike.png'}
							title={'Drumetii MTB'}
							description={
								'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris '
							}
							link={''}
						/>
						<CampTipeItem
							imgSrc={'/camp-types/Ski.png'}
							title={'Tabere SKI'}
							description={
								'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris '
							}
							link={''}
						/>
					</List>
				</Section>
				<section>
					<Typography variant='h2'>Tipuri de tabere</Typography>
					<List>
						<ListItem></ListItem>
						<ListItem></ListItem>
						<ListItem></ListItem>
					</List>
				</section>
			</main>
		</>
	);
}

const BenefitItem = ({
	icon,
	description,
}: {
	icon: string;
	description: string;
}) => {
	return (
		<ListItem>
			<Stack alignItems={'center'}>
				<Image src={icon} alt='brain icon' width={75} height={75} />
				<Typography
					textAlign={'center'}
					fontWeight={600}
					variant='body1'
					style={{ maxWidth: '150px' }}>
					{description}
				</Typography>
			</Stack>
		</ListItem>
	);
};

const Section: React.FC<{
	title: string;
	children: JSX.Element | JSX.Element[];
}> = ({ title, children }) => (
	<section
		style={{ display: 'flex', flexDirection: 'column', alignItems: 'center' }}>
		<Image src={'/sectionIcon.svg'} alt='section icon' width={50} height={50} />
		<Typography fontWeight={600} variant='h4'>
			{title}
		</Typography>
		{children}
	</section>
);
